AlumniConnect/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from os import listdir
from .  import views


favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)
urlpatterns = []

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('login/', views.LoginFormView.as_view(), name='login'),
    #path('account/reset_password/', views.ResetPasswordRequestView.as_view(), name="reset_password"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/',views.signup, name = "signup"),
    path('register/', views.register, name='register'),
    path('newregister/', views.new_register, name='new_register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('confirm/', TemplateView.as_view(template_name='AlumniConnect/confirm_email.html'), name = 'confirm'),
    path('success/', TemplateView.as_view(template_name='AlumniConnect/account_success.html'), name = 'success'),
    re_path('^', include('django.contrib.auth.urls')),
    path('password/', views.change_password, name='change_password'),
    re_path(r'^profileedit/(?P<id>[a-zA-Z0-9]+)/$', views.profileedit, name='profileedit'),
    path('profile/', include('applications.alumniprofile.urls')),
    path('members/', include('applications.members.urls')),
    path('events/', include('applications.events_news.urls')),
    path('news/', include('applications.news.urls')),
    path('newsletter/', include('applications.publications.urls')),
    path('geolocation/', include('applications.geolocation.urls')),
    path('alumnibody/', views.alumniBody),
    path('alumnicard/', views.alumniCard, name='alumnicard'),
    path('gallery/', include('applications.gallery.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('awards/', include('applications.awards.urls')),
    path('chapter/', include('applications.chapter.urls')),
    path('adminportal/', include('applications.adminportal.urls')),
    path('jobs/', include('applications.job_posting.urls')),
    re_path(r'favicon.ico', favicon_view),
    path('constitution/', views.constitution, name='constitution'),
    path('blogs/', include('applications.blog.urls')),
    #path('', views.index, name='home'),
]

if settings.DEBUG:
    

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
admin.site.site_header = "IIITDMJ Alumni Association"
admin.site.site_title = "Alumni Association"
admin.site.index_title = "Alumni Association Admin"

applications/events_news/urls.py
from django.urls import path, re_path

from . import views

app_name = 'events_news'

urlpatterns = [
    re_path(r'^event/(?P<id>[0-9]+)/$', views.event, name='event'),
    path('', views.events, name='events'),
]

applications/events_news/models.py
from django.db import models
import datetime, os
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


def upload_event_photo(instance, filename):
    name, extension = os.path.splitext(filename)
    return "Events/" + str(instance.event_id) + extension

class Event(models.Model):
    event_id = models.AutoField(primary_key = True)
    title = RichTextField()
    start_date = models.DateTimeField(default = datetime.datetime(2019, 1, 1, 12, 0, 0))
    end_date = models.DateTimeField(default = datetime.datetime(2019, 1, 1, 12, 0, 0))
    by = models.CharField(max_length = 255, null=True)
    picture = models.ImageField(null = True, blank = True, upload_to = upload_event_photo)
    location = models.CharField(max_length = 100, null = True)
    address = RichTextUploadingField()
    description = RichTextUploadingField()

    def __str__(self):
        return self.title_stripped

    @property
    def is_completed(self):
        return (timezone.now() > self.end_date)
    
    @property
    def title_stripped(self):
       from django.utils.html import strip_tags
       return strip_tags(self.title)

class Attendees(models.Model):
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = (("event_id", "user_id"),)

applications/events_news/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Event, Attendees
from applications.gallery.models import Album, AlbumImage
from django.db.models import Count
from django.contrib.auth.models import User
from applications.alumniprofile.models import Profile
from django.utils import timezone
from itertools import chain


# Create your views here........
def events(request):
    now = timezone.now()
    events = Event.objects.filter(start_date__gte=now).order_by('start_date').annotate(Count('attendees__user_id'))
    # events_current = Event.objects.filter(start_date__lt=now).filter(end_date__gte=now).order_by('start_date')
    events_completed = Event.objects.filter(end_date__lt=now).order_by('-start_date').annotate(  Count('attendees__user_id'))
    events_ongoing = Event.objects.filter(start_date__lte=now, end_date__gte=now).order_by('start_date').annotate( Count('attendees__user_id'))
    events_to_display = list(chain(events_ongoing, events, events_completed))
    return render(request, "events_news/index.html", {'events': events_to_display})


def event(request, id):
    e = Event.objects.get(event_id=id)
    attending = Attendees.objects.filter(event_id=e).values('user_id__profile__name',
                                                            'user_id__profile__profile_picture', 'user_id__id',
                                                            'user_id__username')  # .exclude(user_id__profile__name=None)
    attendees_limit = 5
    images_limit = 6
    check = False
    album_present = True
    try:
        album = Album.objects.get(event_id=e)
        images = AlbumImage.objects.filter(album=album.id)[:images_limit]
    except:
        album_present = False
        images = list()
        album = ""
    if request.user.is_authenticated:
        try:
            if Attendees.objects.get(user_id=User.objects.get(username=request.user.username), event_id=e):
                check = True
        except:
            pass

    if request.POST.get("submit") == "rsvp":
        if not request.user.is_authenticated:
            return HttpResponseRedirect("/login/?next=" + request.path)

        attendee = Attendees()
        attendee.user_id = User.objects.get(username=request.user.username)
        attendee.event_id = Event.objects.get(event_id=id)
        attendee.save()
        check = True
        return HttpResponseRedirect("/events/event/" + id + "/")

    if request.POST.get("submit") == "rsvp_del":
        if not request.user.is_authenticated:
            return HttpResponseRedirect("/login/?next=" + request.path)

        Attendees.objects.filter(
            user_id=User.objects.get(username=request.user.username),
            event_id=Event.objects.get(event_id=id)
        ).delete()
        return HttpResponseRedirect("/events/event/" + id + "/")

    return render(request, "events_news/event.html", {
        "event": e,
        "check": check,
        "count": attending.count(),
        "count_difference": attending.count() - attendees_limit,
        "attendees": attending,
        "attendees_sliced": attending[:attendees_limit],
        "album_present": album_present,
        "images": images,
        "album": album,
        "base_uri": request.build_absolute_uri()
    })

templates/events_news/index.html
{% extends 'globals/base.html' %}
{% load static %}
{% block css%}
<style>
    .constitution{
        text-align:center;
    }
    .constitutionContainer{
        width:800px;
        height:800px;
    }
    @media (max-width: 768px) {
        .constitutionContainer {
            width: 90%;
            height: 400px;
        }
    }
</style>
{%endblock%}
{% block title %}
    Events
{% endblock %}

{% block body %}
    {% include 'globals/navbar.html' %}
    <div class="p-0 m-0 masthead-bg w-100 parallax shadow-sm" style="min-height:300px !important; height:300px !important; background-position-y: 300px;"></div>
    <!-- <div style="height:150px; min-height: 150px;"></div> -->

    <header class="masthead text-center text-white d-flex" style="height:0px; min-height:300px;">
        <div class="container my-auto" style="margin-bottom:50px !important;">
            <div class="row">
                <div class="col-lg-8 mx-auto align-middle">
                <h1 class="text-uppercase mt-4">
                    <strong>EVENTS</strong>
                </h1>
                </div>
            </div>
        </div>
    </header>
      
    <section id="services" class="bg-primary p-1">
    </section>
    <section id="constitution" class="constitution text-center p-3">
        <h1 class="section-title text-center">Minutes of Meeting - Alumni Meet 2022 </h1>
        <iframe src="{% static 'AlumniConnect/assets/minutes_of_meeting_2022.pdf' %}" class="constitutionContainer"></iframe>
    </section>
    <div class="events-container container text-left p-2 mx-auto my-4">
        {% for item in events %}
            <div class="card shadow bg-light m-4">
                <span class="">
                <div class="row no-gutters p-3">
                    <div class="col-auto mx-auto p-1 pb-3 pb-lg-1">
                        {% if item.picture %}
                        <img src="{{ item.picture.url }}" alt="" height= 200px width= 200px>
                        {% else %}
                        <img src="{% static 'AlumniConnect/img/event.png' %}" alt="" height= 200px width= 200px>
                        {% endif %}
                    </div>
                    
                    <div class="col-lg-9">
                        <div class="card-block px-2">
                            <h2 class="card-title">{{item.title|safe}}</h2>
                            <!-- <p class="m-2 font-weight-normal mb-3"> -->
                            <p class="m-2 font-weight-normal mb-3">
                                <h5>
                                    {% if not item.is_completed %}
                                    <span class="badge badge-pill badge-success"> Upcoming </span>
                                    {% else %}
                                    <span class="badge badge-pill badge-secondary"> Past </span>
                                    {% endif %}
                                    <span class="badge badge-pill badge-dark"> Attendees : {{ item.attendees__user_id__count }} </span>
                                </h5>
                                    
                                <p class="m-1 mt-3">
                                    <i class="fas fa-table mr-2"></i>
                                    {{ item.start_date|date:"d F, o" }}
                                </p>
                                {% if item.location %}
                                <p class="m-1">
                                    <i class="fas fa-map-marker-alt mr-2"></i>&nbsp;
                                    {{ item.location }}
                                </p>
                            {% else %}
                                <p class="m-1">
                                    <i class="fas fa-map-marker-alt mr-2"></i>&nbsp;
                                    N/A
                                </p>
                            {% endif %}
                                {% if item.by %}
                                <p class="m-1">
                                    <i class="fas fa-user mr-2"></i>
                                    {{ item.by }}
                                </p> 
                             {% else %}
                             <p class="m-1">
                                <i class="fas fa-user mr-2"></i>
                                N/A
                            </p> 
                            {% endif %}
                                   
                            </p>
                            <a href="{% url 'events_news:event' id=item.event_id %}" class="btn btn-primary btn-sm card-link px-4 py-2">View</a>
                        </div>
                        <div class="card-footer text-center m-n3">
                            <a href="{% url 'events_news:event' id=item.event_id %}" class="btn btn-primary btn-sm card-link px-4 py-2">View</a>
                        </div>
                        <div class="w-100"></div>
                                
                    </div>
                </div>
                <!-- Footer 
                    <div class="card-footer w-100 text-muted">
                        Footer stating cats are CUTE little animals
                    </div>
                -->
            </div>
            {% endfor %}
        </span>
        </div>
    {% include 'globals/footer.html' %}
{% endblock %}