AlumniConnect/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from os import listdir
from .  import views


favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)
urlpatterns = []

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('login/', views.LoginFormView.as_view(), name='login'),
    #path('account/reset_password/', views.ResetPasswordRequestView.as_view(), name="reset_password"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/',views.signup, name = "signup"),
    path('register/', views.register, name='register'),
    path('newregister/', views.new_register, name='new_register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('confirm/', TemplateView.as_view(template_name='AlumniConnect/confirm_email.html'), name = 'confirm'),
    path('success/', TemplateView.as_view(template_name='AlumniConnect/account_success.html'), name = 'success'),
    re_path('^', include('django.contrib.auth.urls')),
    path('password/', views.change_password, name='change_password'),
    re_path(r'^profileedit/(?P<id>[a-zA-Z0-9]+)/$', views.profileedit, name='profileedit'),
    path('profile/', include('applications.alumniprofile.urls')),
    path('members/', include('applications.members.urls')),
    path('events/', include('applications.events_news.urls')),
    path('news/', include('applications.news.urls')),
    path('newsletter/', include('applications.publications.urls')),
    path('geolocation/', include('applications.geolocation.urls')),
    path('alumnibody/', views.alumniBody),
    path('alumnicard/', views.alumniCard, name='alumnicard'),
    path('gallery/', include('applications.gallery.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('awards/', include('applications.awards.urls')),
    path('chapter/', include('applications.chapter.urls')),
    path('adminportal/', include('applications.adminportal.urls')),
    path('jobs/', include('applications.job_posting.urls')),
    re_path(r'favicon.ico', favicon_view),
    path('constitution/', views.constitution, name='constitution'),
    path('blogs/', include('applications.blog.urls')),
    #path('', views.index, name='home'),
]

if settings.DEBUG:
    

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
admin.site.site_header = "IIITDMJ Alumni Association"
admin.site.site_title = "Alumni Association"
admin.site.index_title = "Alumni Association Admin"

applications/gallery/urls.py
from django.urls import path, re_path

from . import views

app_name = 'gallery'

urlpatterns = [
    # re_path(r'^event/(?P<id>[0-9])/$', views.event, name='event'),
    path('', views.gallery, name='gallery'),
    re_path(r'^(?P<slug>[-\w]+)$', views.AlbumDetail.as_view(), name='album'),

]

applications/gallery/models.py
import uuid
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from applications.events_news.models import Event


class Album(models.Model):
    title = RichTextField()
    description = RichTextUploadingField()
    thumb = ProcessedImageField(upload_to='Albums', processors=[ResizeToFit(300)], format='JPEG',
                                options={'quality': 90})
    tags = RichTextField()
    is_visible = models.BooleanField(default=True)
    created = models.DateTimeField()
    modified = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=255, unique=True)
    event_id = models.ForeignKey(Event, on_delete=models.PROTECT, null=True, blank=True)
    album_link = RichTextUploadingField(null=True, blank=True)

    # def get_absolute_url(self):
    #    return reverse('album', kwargs={'slug':self.slug})

    def __str__(self):
        return self.title_stripped

    @property
    def title_stripped(self):
        from django.utils.html import strip_tags
        return strip_tags(self.title)


class AlbumImage(models.Model):
    image = ProcessedImageField(upload_to='Albums', processors=[ResizeToFit(1280)], format='JPEG',
                                options={'quality': 70})
    thumb = ProcessedImageField(upload_to='Albums', processors=[ResizeToFit(300)], format='JPEG',
                                options={'quality': 80})
    album = models.ForeignKey('album', on_delete=models.CASCADE)
    alt = models.CharField(max_length=255, default=uuid.uuid4)
    created = models.DateTimeField(auto_now_add=True)
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    slug = models.SlugField(max_length=255, default=uuid.uuid4, editable=False)

applications/gallery/forms.py
from django import forms
from .models import Album


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = []

    zip = forms.FileField(required=False)

applications/gallery/views.py
from django.shortcuts import render
from django.http import HttpRequest
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView
from django.db.models import Count
from .models import Album, AlbumImage


def gallery(request):
    album_list = Album.objects.filter(is_visible=True).order_by('-created').annotate(images_count=Count('albumimage'))
    # paginator = Paginator(list, 10)

    # page = request.GET.get('page')
    # try:
    #     albums = paginator.page(page)
    # except PageNotAnInteger:
    #     albums = paginator.page(1) # If page is not an integer, deliver first page.
    # except EmptyPage:
    #     albums = paginator.page(paginator.num_pages) # If page is out of range (e.g.  9999), deliver last page of results.

    return render(request, "gallery/index.html", {'albums': album_list})


class AlbumDetail(DetailView):
    model = Album

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(AlbumDetail, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the images
        images = AlbumImage.objects.filter(album=self.object.id)
        context['images'] = images
        context['images_count'] = images.count()
        return context


def handler404(request, exception):
    assert isinstance(request, HttpRequest)
    return render(request, 'handler404.html', None, None, 404)

templates/gallery/album_detail.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
Gallery
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'external/photoswipe/photoswipe.css' %}">
<link rel="stylesheet" href="{% static 'external/photoswipe/default-skin/default-skin.css' %}">
{% endblock %}

{% block body %}
{% include 'globals/navbar.html' %}
<div class="p-0 m-0 masthead-bg w-100 h-100 parallax" style="min-height:300px !important; height:300px !important; background-position-y: 300px;"></div>

<header class="masthead text-center text-white d-flex" style="height:0px; min-height:300px;">
  <div class="container my-auto" style="margin-bottom:50px !important;">
    <div class="row">
      <div class="col-lg-8 mx-auto align-middle">
        <h1 class="text-uppercase mt-4">
          <strong>GALLERY</strong>
        </h1>
      </div>
    </div>
  </div>
</header>

<section id="services" class="bg-primary p-1">
</section>

<section class="bg-white" id="about" style="padding: 5rem 0;">


  {% if album.is_visible %}
  <div class="container font-open-sans">
    <h1>{{ album.title|safe }}</h1>
    <div>
      <span class="icon-detail"><i class="far fa-calendar-check"></i>
        <time datetime="{{ album.created|date:'Y-m-d' }}">{{ album.created|date:"d M, Y" }}</time>
      </span>
      <span class="icon-detail"><i class="far fa-images"></i>
        {{ images_count }} Photo{{ images_count|pluralize }}
      </span>
    </div>
    <p>{{ album.description|safe }}</p>


    <div class="row">
      {% for item in images %}
      <a class="col-md-4 mb-3" href="javascript:pswpInit({{ forloop.counter0 }});">
        <img src="{{ item.thumb.url }}" style="width: 100%;" class="dpg-album-card-image" alt="{{ item.alt }}" />
      </a>
      {% endfor %}
    </div>


    <div>
      {% if album.album_link %}
      <div><b>Album Link : </b>{{ album.album_link|safe }}</div>
      {% endif %}
      <div><b>Tags</b> : {{ album.tags|safe }}</div>
    </div>
  </div>

  {% include 'globals/init_pwsp.html' %}
  {% else %}
  <h3>This album is temporarily unavailable.</h3>
  {% endif %}

</section>
{% include 'globals/footer.html' %}
{% endblock %}

{% block javascript %}
<script>
  // build the json album images collection 
  window.djangoAlbumImages = [
    {% for item in images %}
    {
      src: '{{ item.image.url }}',
      w: {{ item.width }},
      h: {{ item.height }}
    },
  {% endfor %}
  ];
</script>
<script src="{% static 'external/photoswipe/photoswipe.min.js' %}"></script>
<script src="{% static 'external/photoswipe/photoswipe-ui-default.min.js' %}"></script>
{% endblock %}

templates/gallery/index.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
Gallery
{% endblock %}

{% block body %}
{% include 'globals/navbar.html' %}
<div class="p-0 m-0 masthead-bg w-100 h-100 parallax" style="min-height:300px !important; height:300px !important; background-position-y: 300px;"></div>

<header class="masthead text-center text-white d-flex" style="height:0px; min-height:300px;">
  <div class="container my-auto" style="margin-bottom:50px !important;">
    <div class="row">
      <div class="col-lg-8 mx-auto align-middle">
        <h1 class="text-uppercase mt-4">
          <strong>GALLERY</strong>
        </h1>
      </div>
    </div>
  </div>
</header>

<section id="services" class="bg-primary p-1">
</section>

<section class="bg-white" id="about" style="padding: 5rem 0 3rem;">

  <div class="container px-sm-0 px-md-4 px-xl-2 font-open-sans">
    <div class="row w-100 mx-auto">
      {% for album in albums %}
      <div class="col-sm-6 col-lg-4 col-xl-3 d-flex justify-content-center mb-5 px-sm-2 px-md-4 px-lg-3 px-xl-2">
        <div class="card dpg-album-card w-100">
          <img src="{{ album.thumb.url }}" alt="{{ album.title }}" class="card-image-top dpg-album-card-image w-100" />
          <div class="card-body">
            <h5 class="card-title">{{ album.title|safe }}</h5>
            <i class="far fa-images"></i>{{ album.images_count }} Photo{{ album.images_count|pluralize }}
            <p class="card-text">{{ album.description|safe|truncatechars:200 }}</p>
          </div>
          <div class="card-footer">
            <h5 class="text-muted text-center m-0 py-2">
              <a class="btn btn-primary btn-sm py-2 px-4" href="{% url 'gallery:album' album.slug %}">View Album</a>
            </h5>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

</section>
{% include 'globals/footer.html' %}
{% endblock %}