AlumniConnect/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView

from os import listdir
from .  import views


favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)
urlpatterns = []

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('login/', views.LoginFormView.as_view(), name='login'),
    #path('account/reset_password/', views.ResetPasswordRequestView.as_view(), name="reset_password"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/',views.signup, name = "signup"),
    path('register/', views.register, name='register'),
    path('newregister/', views.new_register, name='new_register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('confirm/', TemplateView.as_view(template_name='AlumniConnect/confirm_email.html'), name = 'confirm'),
    path('success/', TemplateView.as_view(template_name='AlumniConnect/account_success.html'), name = 'success'),
    re_path('^', include('django.contrib.auth.urls')),
    path('password/', views.change_password, name='change_password'),
    re_path(r'^profileedit/(?P<id>[a-zA-Z0-9]+)/$', views.profileedit, name='profileedit'),
    path('profile/', include('applications.alumniprofile.urls')),
    path('members/', include('applications.members.urls')),
    path('events/', include('applications.events_news.urls')),
    path('news/', include('applications.news.urls')),
    path('newsletter/', include('applications.publications.urls')),
    path('geolocation/', include('applications.geolocation.urls')),
    path('alumnibody/', views.alumniBody),
    path('alumnicard/', views.alumniCard, name='alumnicard'),
    path('gallery/', include('applications.gallery.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('awards/', include('applications.awards.urls')),
    path('chapter/', include('applications.chapter.urls')),
    path('adminportal/', include('applications.adminportal.urls')),
    path('jobs/', include('applications.job_posting.urls')),
    re_path(r'favicon.ico', favicon_view),
    path('constitution/', views.constitution, name='constitution'),
    path('blogs/', include('applications.blog.urls')),
    #path('', views.index, name='home'),
]

if settings.DEBUG:
    

    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
admin.site.site_header = "IIITDMJ Alumni Association"
admin.site.site_title = "Alumni Association"
admin.site.index_title = "Alumni Association Admin"

applications/jobs/urls.py
from django.urls import path, re_path

from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.add_opportunity, name='add_opportunity'),
    path('filter/', views.filter, name='filter'),
    re_path(r'^del/(?P<i_id>[0-9]+)/$', views.delete_job, name='delete_job'),
]

applications/jobs/models.py
from django.db import models
from django.contrib.auth.models import User

#Opportunity
class Job(models.Model):
    job_role = models.CharField(max_length=20, null=False) #job role
    org_name = models.CharField(max_length=25, null=False) #org_name
    type = models.CharField(max_length=20)
    link = models.URLField(max_length=1000)
    stipend = models.IntegerField(null=True, blank=True)
    exp_req = models.IntegerField(null=True, blank=True)
    tenure = models.IntegerField(null=True, blank=True)
    last_date = models.DateField(null=True, blank=True)
    join_date = models.DateField(null=True, blank=True)
    job_desc = models.CharField(max_length=300, help_text="Brief Description of job profile", null=True, blank=True)#job_desc
    person = models.ForeignKey(User, on_delete=models.CASCADE)#added_by
    posting_date = models.DateField()
    location = models.CharField(max_length=30, null=False)
    active = models.BooleanField(null=False, default=True)

    def __str__(self):
        return self.job_role + " at " + self.org_name #job_role at org_name

applications/jobs/views.py
from django.shortcuts import render
from .models import Job
from datetime import date
from django.contrib import messages
from django.shortcuts import redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.urls import reverse_lazy


def is_superuser(user):
    return user.is_superuser


@login_required
def index(request):
    posts = Job.objects.all().filter(active=True).order_by('-posting_date') 
    total = len(posts) 
    page = request.GET.get('page', 1)
    if posts:
        # using paginator to list 10 jobs at a page
        paginator = Paginator(posts, 10)
        try:
            current_page = paginator.page(page) 
        except PageNotAnInteger:
            current_page = paginator.page(1)
        except EmptyPage:
            current_page = paginator.page(paginator.num_pages)
        if request.user.is_superuser:
            # retrieving jobs of current_page into a list using zip 
            # it will pair job with person
            person_list = [] 
            for i in posts:
                person_list.append(i.person)
            job_list = zip(current_page, person_list)
            return render(request, "jobs/job_home.html", {'job_list': job_list, 'current_page': current_page, 'total': total})
        else:
            person_list = []
            for i in posts:
                person_list.append(i.person)
            job_list = zip(current_page, person_list)
            return render(request, "jobs/job_home.html", {'job_list': job_list, 'current_page': current_page, 'total': total})
    else:
        job_list = []
        return render(request, "jobs/job_home.html", {'job_list': job_list, 'total': total})


@login_required
def filter(request):
    viewname = "filter"
    job_role = request.POST.get('position')
    page = request.GET.get('page', 1)
    type = request.POST.get('type')

    if job_role != 'all' and type != 'all':
        posts = Job.objects.filter(job_role=job_role, type=type, active=True).order_by('-posting_date')
    elif job_role != 'all' and type == 'all':
        posts = Job.objects.filter(job_role=job_role, active=True).order_by('-posting_date')
    elif job_role == 'all' and type != 'all':
        posts = Job.objects.filter(type=type, active=True).order_by('-posting_date')
    else:
        return redirect('jobs:index', permanent=True)

    if posts:
        messages.success(request, "Found " + str(posts.count()) + " posts matching your query!")
        paginator = Paginator(posts, 10)
        try:
            current_page = paginator.page(page)
        except PageNotAnInteger:
            current_page = paginator.page(1)
        except EmptyPage:
            current_page = paginator.page(paginator.num_pages)
        person_list = []
        for i in posts:
            person_list.append(i.person)
            job_list = zip(current_page, person_list)
        return render(request, "jobs/job_home.html", {'job_list': job_list, 'current_page': current_page, 'viewname': viewname})

    else:
        job_list = []
        messages.error(request, "No posts matching your current requirements.")
        return render(request, "jobs/job_home.html", {'job_list': job_list, 'viewname': viewname})


@login_required
def add_opportunity(request):
    if request.method == 'POST':
        try:
            type = request.POST.get('type')
            job_role = request.POST.get('position')
            org_name = request.POST.get('company')
            location = request.POST.get('location')
            raw_link = request.POST.get('link')
            link = raw_link if raw_link.startswith('https://') or raw_link.startswith(
                'http://') else 'https://' + raw_link

            job_desc = request.POST.get('desc')
            stipend = int(request.POST.get('stipend')) if request.POST.get('stipend') else None
            exp_req = int(request.POST.get('exp_req')) if request.POST.get('exp_req') else None
            tenure = int(request.POST.get('tenure')) if request.POST.get('tenure') else None
            last_date = request.POST.get('last_date') if request.POST.get('last_date') else None
            join_date = request.POST.get('join_date') if request.POST.get('join_date') else None
            person = User.objects.get(username=str(request.user))

            insert = Job.objects.create(type=type, job_role=job_role, org_name=org_name, location=location, job_desc=job_desc,
                                        stipend=stipend, exp_req=exp_req, last_date=last_date, join_date=join_date,
                                        tenure=tenure, link=link, posting_date=date.today(), person=person, active=True)
            print(insert)
            messages.success(request, "Job opportunity added successfully!")

        except Exception as e:
            messages.error(request, "Some error occurred, try again.")
            print("Exception while adding new job: ", e)

        return redirect('jobs:index', permanent=True)

    return render(request, "jobs/add_opportunity.html")


@login_required
@user_passes_test(
    is_superuser, redirect_field_name=None,
    login_url=reverse_lazy('home')
)
def delete_job(request, job_id=None):
    if job_id:
        job_post = Job.objects.get(id=job_id)
        job_post.active = False
        job_post.save()
        messages.success(request, "Job opportunity removed successfully!")

    return redirect('jobs:index', permanent=True)

templates/jobs/add_opportunity.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
    Post
{% endblock %}

{% block css %}
    <style type="text/css">
        .detail {
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block body %}
    {% include 'globals/navbar.html' %}
    {% include 'globals/theme.html' with heading='Add Job' %}
    <br>
    <br>

    <section style="padding:0 0 4rem;">
        <div class="container text-center p-0">
            <div class="row">
                <div class="col">
                    <a href="{% url 'jobs:index' %}" class="btn btn-dark btn-outline-primary m-3 text-white">
                        <i class="fa fa-arrow-left mr-2" style="color:inherit !important"
                           aria-hidden="true"></i>
                        Go back to job opportunities
                    </a>
                </div>
            </div>
        </div>

        <div class="container text-left mt-5 pt-4 shadow-lg rounded">
            <form name="new_post" action="{% url 'jobs:add_opportunity' %}" method="POST">{% csrf_token %}

                <div class="row m-4">
                    <div class="col text-center">
                        <span class="mx-auto text-uppercase h3"><strong>Post a new job here !</strong></span><br>
                    </div>
                </div>

                <div class="row m-4">
                    <div class="mx-auto col-sm-5">
                        <label for="type">Type <span class="text-danger">*</span>:</label>
                        <select required class="form-control" name="type" id="type">
                            <option disabled selected value> -- select an option --</option>
                            <option value="Internship">Internship</option>
                            <option value="Full Time">Full Time</option>
                            <option value="Both">Both</option>
                        </select>
                    </div>

                    <div class="mx-auto col-sm-5">
                        <label for="position">Position <span class="text-danger">*</span>:</label>
                        <select required class='form-control' name="position" id="position">
                            <option disabled selected value> -- select an option --</option>
                            <option value="Software Developer">Software Developer</option>
                            <option value="Data Engineer">Data Engineer</option>
                            <option value="Android">Android</option>
                            <option value="IoS">IoS</option>
                            <option value="Software Engineer">Software Engineer</option>
                            <option value="Data Analytics">Data Analytics</option>
                            <option value="Data Science">Data Science</option>
                            <option value="Machine Learning">Machine Learning</option>
                            <option value="Business Development">Business Development</option>
                            <option value="Research">Research</option>
                            <option value="Blockchain">Blockchain</option>
                            <option value="UI/UX Designer">UI/UX Designer</option>
                            <option value="Marketing and Sales">Marketing and Sales</option>
                            <option value="Other">Other</option>
                        </select>
                    </div>
                </div>

                <div class="row m-4">
                    <div class="mx-auto col-sm-5">
                        <label for="company">Company <span class="text-danger">*</span>:</label>
                        <input required class="form-control" type="text" name="company" id='company'>
                    </div>

                    <div class="mx-auto col-sm-5">
                        <label for="location">Location <span class="text-danger">*</span>:</label>
                        <input required class="form-control" type="text" name="location" id='location'>
                    </div>
                </div>

                <div class="row m-4">
                    <div class="mx-auto col-sm-10">
                        <label for="link">Link to apply <span class="text-danger">*</span>:</label>
                        <input required class="form-control" type=text name="link" id='link'>
                    </div>
                </div>

                <div class="row m-4">
                    <div class="mx-auto col-sm-10">
                        <label for="desc">Job description:</label>
                        <textarea class="form-control" rows="4" cols="50" name="desc" form="new_post" id='desc'>
                        </textarea>
                    </div>
                </div>

                <div class="row m-4">
                    <div class="mx-auto col-3">
                        <label for="stipend">Stipend <a class="detail">(Per Month)</a>:</label>
                        <input class="form-control" type="number" name="stipend" id='stipend'>
                    </div>

                    <div class="mx-auto col-3">
                        <label for="tenure">Tenure <a class="detail">(In Months)</a>:</label>
                        <input class="form-control" type="number" name="tenure" id='tenure'>
                    </div>

                    <div class="mx-auto col-3">
                        <label for="exp_req">Min. Experience <a class="detail">(In years)</a>:</label>
                        <input class="form-control" type="number" name="exp_req" id='exp_req'>
                    </div>
                </div>

                <div class="row m-4">
                    <div class="mx-auto col-sm-5">
                        <label for="last_date">Last Date to apply:</label>
                        <input class="form-control" type="date" name="last_date" id='last_date'>
                    </div>

                    <div class="mx-auto col-sm-5">
                        <label for="join_date">Joining date:</label>
                        <input class="form-control" type="date" name="join_date" id='join_date'>
                    </div>
                </div>

                <div class="row p-4">
                    <div class="mx-auto text-center col-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>

            </form>
        </div>
    </section>


    {% include 'globals/footer.html' %}
{% endblock %}

templates/jobs/job_home.html
{% extends 'globals/base.html' %}
{% load static %}

{% block title %}
    Job Opportunities
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'jobs/job_home.css' %}" />
{% endblock %}

{% block body %}
    {% include 'globals/navbar.html' %}
    {% include 'globals/theme.html' with heading='Jobs' %}

    <!-- search section -->
    <section class="bg-light" style="padding:0 !important;">
        <div class="container text-left mx-auto bg-light" style="padding:0 !important;">
            <div class="row w-100 mx-auto bg-primary rounded-bottom">
                <div class="col text-white text-center p-0 pt-4 pb-4">

                    <br>
                    <span class="mx-auto text-uppercase h3"><strong>Search</strong></span><br>
                    <span class="mx-auto h6">from</span>
                    <span class="mx-auto h6">{{ total }} jobs posted here</span>

                    <div class="search-container m-3 p-3" style="margin:6px;">
                        {% if viewname != 'filter' %}
                            <form name="filter" action="{% url 'jobs:filter' %}" method="post">{% csrf_token %}
                                <div class="row justify-content-center m-3">
                                    <select class='form-control col-4 mx-2' name="position" id="position1">
                                        <option selected value="all">Any Position</option>
                                        <option value="Software Developer">Software Developer</option>
                                        <option value="Data Engineer">Data Engineer</option>
                                        <option value="Android">Android</option>
                                        <option value="IoS">IoS</option>
                                        <option value="Software Engineer">Software Engineer</option>
                                        <option value="Data Analytics">Data Analytics</option>
                                        <option value="Data Science">Data Science</option>
                                        <option value="Machine Learning">Machine Learning</option>
                                        <option value="Business Development">Business Development</option>
                                        <option value="Research">Research</option>
                                        <option value="Blockchain">Blockchain</option>
                                        <option value="UI/UX Designer">UI/UX Designer</option>
                                        <option value="Marketing and Sales">Marketing and Sales</option>
                                        <option value="Other">Other</option>
                                    </select>

                                    <select class='form-control col-4 mx-2' name="type" id="type1">
                                        <option selected value="all">Any Role</option>
                                        <option value="Full Time">Full Time</option>
                                        <option value="Internship">Internship</option>
                                        <option value="Both">Both</option>
                                    </select>
                                    <button type="submit" class="btn btn-dark col-1 rounded mx-2">
                                        <i class="fa fa-search mx-auto"></i>
                                    </button>
                                </div>
                            </form>
                        {% else %}
                            <a href="{% url 'jobs:index' %}" class="btn btn-dark btn-outline-primary m-3 text-white">
                                <i class="fa fa-arrow-left mr-2" style="color:inherit !important"
                                   aria-hidden="true"></i>
                                See all posts
                            </a>
                        {% endif %}
                    </div>

                    <a href="{% url 'jobs:add_opportunity' %}" class="btn btn-dark btn-outline-primary mb-2 text-white">
                        <i class="fa fa-plus-square mr-2" style="color:inherit !important" aria-hidden="true"></i>
                        Want to add an opportunity?
                    </a>

                </div>
            </div>
        </div>
    </section>

    <!-- job opportunity list -->
    <section class="bg-light" style="padding:2rem 0 2rem;">
        <div class="container text-left mx-auto bg-light" style="padding-top:0 !important">

            {% for message in messages %}
                <div class="alert alert-primary alert-dismissible fade show mb-4" role="alert">
                    <strong>Message : </strong> {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}


            {% if job_list %}
                <div class="row">
                    {% for job, person in job_list %}
                        <div class="col-lg-6 px-5">
                            <div class="card mb-5 shadow-lg">
                                <div class="card-header bg-primary font-open-sans">
                                    <div class="row">

                                        <div class="col mx-auto text-left">
                                            <a style="color:white; font-size: 25px">{{ job.job_role|title }}</a><br>
                                            <a style="color: rgba(255, 255, 255, 0.7); font-size: 18px;">{{ job.org_name|title }}</a>
                                        </div>

                                        <div class="col-4 mx-auto text-right">
                                            <a href="{{ job.link }}" class="btn btn-light">
                                                Apply <i class="fa fa-link"></i>
                                            </a>
                                            {% if request.user.is_superuser %}
                                                <a href="{% url 'jobs:delete_job' job.id %}" class="btn btn-danger mt-1"
                                                   role="button">Remove <i class="fa fa-trash-alt text-white"></i></a>
                                            {% endif %}
                                        </div>

                                    </div>
                                </div>

                                <div class="card-body">
                                    <div class="container">

                                        <div class="row mb-4">
                                            <div class="col">
                                                <i class="fa fa-map-marker-alt" aria-hidden="true"></i>
                                                <a class="detail">{{ job.type }} in {{ job.location|title }}</a>
                                            </div>
                                        </div>

                                        <div class="row mb-4">
                                            <div class="col-md-4 mb-2">
                                                <div class="heading">
                                                    <i class="fa fa-money-bill" aria-hidden="true"></i><a>Stipend</a>
                                                </div>
                                                {% if job.stipend != None %}
                                                    <a class="detail">₹ {{ job.stipend }}/ Month</a>
                                                {% else %}
                                                    <a class="detail">Unknown</a>
                                                {% endif %}
                                            </div>

                                            {% if job.exp_req %}
                                                <div class="col-md-4 mb-2">
                                                    <div class="heading">
                                                        <i class="fa fa-briefcase"></i><a>Exp Required</a>
                                                    </div>
                                                    <a class="detail">{{ job.exp_req }} Years</a>
                                                </div>
                                            {% endif %}
                                        </div>

                                        <div class="row mb-4">
                                            <div class="col-md-4 mb-2">
                                                <div class="heading">
                                                    <i class="fa fa-calendar"></i><a>Apply By</a>
                                                </div>
                                                <a class="detail">{{ job.last_date }}</a>
                                            </div>

                                            <div class="col-md-4 mb-2">
                                                <div class="heading">
                                                    <i class="fa fa-calendar"></i><a>Join Date</a>
                                                </div>
                                                {% if job.join_date %}
                                                    <a class="detail">{{ job.join_date }}</a>
                                                {% else %}
                                                    <a class="detail">Immediately</a>
                                                {% endif %}
                                            </div>

                                            {% if job.tenure %}
                                                <div class="col-md-4 mb-2">
                                                    <div class="heading">
                                                        <i class="fa fa-calendar"></i><a>Tenure</a>
                                                    </div>
                                                    <a class="detail">{{ job.tenure }} Months</a>
                                                </div>
                                            {% endif %}
                                        </div>

                                        {% if job.desc %}
                                            <div class="row mb-4">
                                                <div class="col">
                                                    <div class="heading">
                                                        <i class="icon icofont-notepad"></i><a>Description</a>
                                                    </div>
                                                    <div id="more">
                                                        <p class="detail colapse"
                                                           id="collapseExample{{ forloop.counter }}"
                                                           aria-exapanded="false">{{ job.desc }}</p>
                                                        <a role="button" class="collapsed" data-toggle="collapse"
                                                           href="#collapseExample{{ forloop.counter }}"
                                                           aria-expanded="false" aria-controls="collapseExample"
                                                           style="font-size: 16px;"></a>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endif %}

                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

            {% else %}
                <div class="row col">
                    <span class="mx-auto mt-2 h3">No job posts :(</span>
                </div>
            {% endif %}


            {% if current_page.has_other_pages %}
                <ul class="pagination" style="justify-content: center;">
                    {% if current_page.has_previous %}
                        <li class="m-1"><a href="?page={{ current_page.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled m-1"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in current_page.paginator.page_range %}
                        {% if current_page.number == i %}
                            <li class="active m-1"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="m-1"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if current_page.has_next %}
                        <li class="m-1"><a href="?page={{ current_page.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled m-1"><span>&raquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}

        </div>
    </section>


    {% include 'globals/footer.html' %}
{% endblock %}